#!/bin/bash

echo ""

echo "Copying Bash Profile..."
cp -f /Users/garyperrigo/GitHub/dotfiles/.bash_profile ~/.bash_profile
cp -f ~/Github/dotfiles/.bash_profile ~/.bashrc

echo "Copying Bash Alias Files..."
cp /Users/garyperrigo/GitHub/dotfiles/.bashconfigs/bashalias /Users/garyperrigo/.bashconfigs/bashalias

echo "Executing OSX Config Files..."
bash ~/GitHub/dotfiles/.osx

echo "Copying Screen Config..."
cp ~/GitHub/dotfiles/.screenrc ~/

echo "Copying Atom Config.."
cp -R ~/GitHub/dotfiles/.atom ~/

echo "Reloading Bash.."
source ~/.bash_profile

echo ""
